In [2]:
def grav(m1, m2, r):
    F=m1*m2/r**2
    return F

In [2]:
grav(2,3,1)

NameError: name 'grav' is not defined

In [5]:
for i in range(1,5):
    print ('m1:',i, 'm2',i**3,i,'F:',grav(i,i**3,i))

('m1:', 1, 'm2', 1, 1, 'F:', 1)
('m1:', 2, 'm2', 8, 2, 'F:', 4)
('m1:', 3, 'm2', 27, 3, 'F:', 9)
('m1:', 4, 'm2', 64, 4, 'F:', 16)


In [9]:
##Random Walk 10
import matplotlib.pyplot as plt
import random
def walk1D(x0,N,d):
    X=[] #store position
    T=[] #store step
    for t in range(N):
        x=x0+random.choice([-1,1])*d
        T.append(t)
        X.append(x)
    return T,X        

In [10]:
walk1D(0,10,1)

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [-1, 1, -1, -1, 1, -1, -1, -1, -1, 1])

In [11]:
time,pos=walk1D(0,100,1)

In [19]:
#numpy 
import numpy as np
#create array from list
L=[1,2]
type(L)
M=np.array(L)
type(M)

numpy.ndarray

In [20]:
import matplotlob.pyplot as plt
import seaborn as sns
sns.set()
plt.figure(figsize=[10,6])
sns.heatmap(X,annot=two)

ImportError: No module named matplotlob.pyplot

In [21]:
X=np.arange(35)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [24]:
XX=np.reshape(X,(7,5))
np.shape(XX)

(7L, 5L)

In [25]:
Y=XX.flatten()
Y.shape

(35L,)

In [26]:
A=np.random.randint(0,4,[2,3])
B=np.random.randint(0,4,[2,3])
A,B

(array([[2, 1, 1],
        [2, 3, 0]]), array([[3, 3, 2],
        [3, 1, 0]]))

In [27]:
C=np.concatenate((A,B),axis=0)
C

array([[2, 1, 1],
       [2, 3, 0],
       [3, 3, 2],
       [3, 1, 0]])

In [30]:
D=np.concatenate((A,B),axis=1)
D

array([[2, 1, 1, 3, 3, 2],
       [2, 3, 0, 3, 1, 0]])

In [31]:
print(D.sum(),D.sum(axis=0),D.sum(axis=1))

(21, array([4, 4, 1, 6, 4, 2]), array([12,  9]))


In [35]:
print(D.sum(),D.sum(axis=0))

(21, array([4, 4, 1, 6, 4, 2]))


In [38]:
#meshgrid is useful to evaluate a function on a grid
x=np.arange(-5,5,0.05)
y=np.arange(-5,5,0.05)
grid=np.meshgrid(x,y)
print(len(x),len(y),len(grid),len(grid[0]))

(200, 200, 2, 200)


In [45]:
#Matrix Algebra
import numpy as np
import random

In [46]:
A=np.random.randint(0,4,[3,1])
B=np.random.randint(0,4,[1,3])
A,B

(array([[3],
        [2],
        [3]]), array([[2, 0, 3]]))

In [47]:
C=np.dot(A,B)
C

array([[6, 0, 9],
       [4, 0, 6],
       [6, 0, 9]])

In [48]:
C.T

array([[6, 4, 6],
       [0, 0, 0],
       [9, 6, 9]])

In [49]:
#solve Ax=B
A=np.random.randint(0,4,[3,3])
B=np.random.randint(0,4,[3,1])

In [50]:
import numpy.linalg as LA
LA.solve(A,B)

array([[-0.66666667],
       [ 1.33333333],
       [ 0.33333333]])

In [51]:
A_inv=LA.inv(A)
A_inv

array([[ 0.33333333,  0.        , -0.33333333],
       [ 0.33333333, -0.33333333,  0.33333333],
       [-0.66666667,  0.66666667,  0.33333333]])

In [54]:
np.dot(A_inv,A)

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   5.55111512e-17],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])